// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	models "calendar/internal/models"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockRepo) CreateEvent(ctx context.Context, event models.Events) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, event)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockRepoMockRecorder) CreateEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockRepo)(nil).CreateEvent), ctx, event)
}

// DeleteEvent mocks base method.
func (m *MockRepo) DeleteEvent(ctx context.Context, delEventID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", ctx, delEventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockRepoMockRecorder) DeleteEvent(ctx, delEventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockRepo)(nil).DeleteEvent), ctx, delEventID)
}

// EventsForDay mocks base method.
func (m *MockRepo) EventsForDay(ctx context.Context, userID int, date time.Time) ([]models.Events, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventsForDay", ctx, userID, date)
	ret0, _ := ret[0].([]models.Events)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventsForDay indicates an expected call of EventsForDay.
func (mr *MockRepoMockRecorder) EventsForDay(ctx, userID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventsForDay", reflect.TypeOf((*MockRepo)(nil).EventsForDay), ctx, userID, date)
}

// EventsForMonth mocks base method.
func (m *MockRepo) EventsForMonth(ctx context.Context, userID int, date time.Time) ([]models.Events, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventsForMonth", ctx, userID, date)
	ret0, _ := ret[0].([]models.Events)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventsForMonth indicates an expected call of EventsForMonth.
func (mr *MockRepoMockRecorder) EventsForMonth(ctx, userID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventsForMonth", reflect.TypeOf((*MockRepo)(nil).EventsForMonth), ctx, userID, date)
}

// EventsForWeek mocks base method.
func (m *MockRepo) EventsForWeek(ctx context.Context, userID int, date time.Time) ([]models.Events, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventsForWeek", ctx, userID, date)
	ret0, _ := ret[0].([]models.Events)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventsForWeek indicates an expected call of EventsForWeek.
func (mr *MockRepoMockRecorder) EventsForWeek(ctx, userID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventsForWeek", reflect.TypeOf((*MockRepo)(nil).EventsForWeek), ctx, userID, date)
}

// FindEvents mocks base method.
func (m *MockRepo) FindEvents(ctx context.Context, eventID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindEvents", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindEvents indicates an expected call of FindEvents.
func (mr *MockRepoMockRecorder) FindEvents(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindEvents", reflect.TypeOf((*MockRepo)(nil).FindEvents), ctx, eventID)
}

// UpdateEvent mocks base method.
func (m *MockRepo) UpdateEvent(ctx context.Context, updEvent models.Events) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", ctx, updEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockRepoMockRecorder) UpdateEvent(ctx, updEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockRepo)(nil).UpdateEvent), ctx, updEvent)
}
