// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	dto "calendar/internal/dto"
	models "calendar/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEventService is a mock of EventService interface.
type MockEventService struct {
	ctrl     *gomock.Controller
	recorder *MockEventServiceMockRecorder
}

// MockEventServiceMockRecorder is the mock recorder for MockEventService.
type MockEventServiceMockRecorder struct {
	mock *MockEventService
}

// NewMockEventService creates a new mock instance.
func NewMockEventService(ctrl *gomock.Controller) *MockEventService {
	mock := &MockEventService{ctrl: ctrl}
	mock.recorder = &MockEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventService) EXPECT() *MockEventServiceMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockEventService) CreateEvent(ctx context.Context, event dto.RequestDTO) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, event)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockEventServiceMockRecorder) CreateEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockEventService)(nil).CreateEvent), ctx, event)
}

// DeleteEvent mocks base method.
func (m *MockEventService) DeleteEvent(ctx context.Context, delEventID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", ctx, delEventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockEventServiceMockRecorder) DeleteEvent(ctx, delEventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockEventService)(nil).DeleteEvent), ctx, delEventID)
}

// EventsForDay mocks base method.
func (m *MockEventService) EventsForDay(ctx context.Context, userID int, date string) ([]models.Events, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventsForDay", ctx, userID, date)
	ret0, _ := ret[0].([]models.Events)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventsForDay indicates an expected call of EventsForDay.
func (mr *MockEventServiceMockRecorder) EventsForDay(ctx, userID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventsForDay", reflect.TypeOf((*MockEventService)(nil).EventsForDay), ctx, userID, date)
}

// EventsForMonth mocks base method.
func (m *MockEventService) EventsForMonth(ctx context.Context, userID int, date string) ([]models.Events, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventsForMonth", ctx, userID, date)
	ret0, _ := ret[0].([]models.Events)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventsForMonth indicates an expected call of EventsForMonth.
func (mr *MockEventServiceMockRecorder) EventsForMonth(ctx, userID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventsForMonth", reflect.TypeOf((*MockEventService)(nil).EventsForMonth), ctx, userID, date)
}

// EventsForWeek mocks base method.
func (m *MockEventService) EventsForWeek(ctx context.Context, userID int, date string) ([]models.Events, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventsForWeek", ctx, userID, date)
	ret0, _ := ret[0].([]models.Events)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventsForWeek indicates an expected call of EventsForWeek.
func (mr *MockEventServiceMockRecorder) EventsForWeek(ctx, userID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventsForWeek", reflect.TypeOf((*MockEventService)(nil).EventsForWeek), ctx, userID, date)
}

// UpdateEvent mocks base method.
func (m *MockEventService) UpdateEvent(ctx context.Context, eventDTO dto.RequestDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", ctx, eventDTO)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockEventServiceMockRecorder) UpdateEvent(ctx, eventDTO interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockEventService)(nil).UpdateEvent), ctx, eventDTO)
}
